name: Cache Test

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner to use'
        required: true
        default: 'ubuntu-latest'

jobs:
  cache-test:
    runs-on: ${{ github.event.inputs.runner }}

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4

      - name: Test ACTION_CACHE_URL override pre
        env:
          ACTIONS_CACHE_URL: https://cache-pre
        uses: actions/github-script@v7
        with:
          script: |
            console.log(`ACTIONS_CACHE_URL: ${process.env.ACTIONS_CACHE_URL}`);

      - name: Overwrite Runner
        shell: bash
        run: |
          # Find path to runner file (~/runners/<version>/bin/Runner.Worker.dll)
          RUNNER_PATH=$(find ~/ -type f -name Runner.Worker.dll | head -n 1)
          echo "Runner.Worker.dll path: $RUNNER_PATH"
          # Overwrite ACTIONS_CACHE_URL with ACTION_CACHES_ORL
          sed -i 's/\x41\x00\x43\x00\x54\x00\x49\x00\x4F\x00\x4E\x00\x53\x00\x5F\x00\x43\x00\x41\x00\x43\x00\x48\x00\x45\x00\x5F\x00\x55\x00\x52\x00\x4C\x00/\x41\x00\x43\x00\x54\x00\x49\x00\x4F\x00\x4E\x00\x53\x00\x5F\x00\x43\x00\x41\x00\x43\x00\x48\x00\x45\x00\x5F\x00\x4F\x00\x52\x00\x4C\x00/g' "$RUNNER_PATH"

      - name: Test ACTION_CACHE_URL override post
        env:
          ACTIONS_CACHE_URL: https://cache-post
        uses: actions/github-script@v7
        with:
          script: |
            console.log(`ACTIONS_CACHE_URL: ${process.env.ACTIONS_CACHE_URL}`);

      - name: JWT Payload
        uses: actions/github-script@v7
        with:
          script: |
            // Get the JWT payload from $ACTIONS_RUNTIME_TOKEN
            const jwt = process.env.ACTIONS_RUNTIME_TOKEN;
            const payload = jwt.split('.')[1];
            const buff = Buffer.from(payload, 'base64');
            const text = buff.toString('utf-8');
            const parsed = JSON.parse(text);
            console.log(JSON.stringify(parsed, null, 2));

      - name: Setup tmate session
        if: ${{ github.event.inputs.runner != 'self-hosted' }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
        with:
          limit-access-to-actor: true

